steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'us-central1-docker.pkg.dev/arctic-sentry-467317-s7/notebook-repo/notebook-service:v1', '.']

  - name: gcr.io/cloud-builders/docker
    args: ['push', 'us-central1-docker.pkg.dev/arctic-sentry-467317-s7/notebook-repo/notebook-service:v1']

# Images to be built and pushed by this build
images:
  - us-central1-docker.pkg.dev/arctic-sentry-467317-s7/notebook-repo/notebook-service:v1

# Options for the entire build. This is a top-level key.
options:
  # logging: CLOUD_LOGGING_ONLY # This is commented out.
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

  #    - '--region'
  #    - us-central1
  #    - '--platform'
  #    - managed
  #    - '--allow-unauthenticated'
  #    - '--memor-1Gi'
  #    - '--cpu=1'
  #    - port=8080
