services:
  cloud-sql-proxy:
    image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.14.0
    restart: unless-stopped
    command:
      - "--address=0.0.0.0"
      - "--port=5432"
      - "arctic-sentry-467317-s7:us-central1:studenthub"
    networks:
      - edhub360

  login:
    build: ./login
    restart: unless-stopped
    env_file: ./login/env.prod
    depends_on:
      - cloud-sql-proxy
    ports:
      - "127.0.0.1:8001:8080"
    networks:
      - edhub360

  subscription:
    build: ./subscription
    restart: unless-stopped
    env_file: ./subscription/env.prod
    depends_on:
      - cloud-sql-proxy
    ports:
      - "127.0.0.1:8002:8080"
    networks:
      - edhub360

  ai_chat:
    build: ./ai_chat
    restart: unless-stopped
    env_file: ./ai_chat/env.prod
    depends_on:
      - cloud-sql-proxy
    ports:
      - "127.0.0.1:8003:8080"
    volumes:
      - ai_chat_data:/app/data
    networks:
      - edhub360

  flashcard:
    build: ./flashcard
    restart: unless-stopped
    env_file: ./flashcard/env.prod
    depends_on:
      - cloud-sql-proxy
    ports:
      - "127.0.0.1:8004:8080"
    networks:
      - edhub360

  quiz:
    build: ./quiz
    restart: unless-stopped
    env_file: ./quiz/env.prod
    depends_on:
      - cloud-sql-proxy
    ports:
      - "127.0.0.1:8005:8080"
    networks:
      - edhub360

  study_planner:
    build: ./study_planner
    restart: unless-stopped
    env_file: ./study_planner/env.prod
    depends_on:
      - cloud-sql-proxy
    ports:
      - "127.0.0.1:8006:8080"
    networks:
      - edhub360

  cs_bot:
    build: ./cs_bot
    restart: unless-stopped
    env_file: ./cs_bot/env.prod
    depends_on:
      - cloud-sql-proxy
    ports:
      - "127.0.0.1:8007:8080"
    networks:
      - edhub360

  Notes:
    build: ./Notes
    image: edhub360-notes
    restart: unless-stopped
    env_file: ./Notes/env.prod
    depends_on:
      - cloud-sql-proxy
    ports:
      - "127.0.0.1:8008:8080"
    networks:
      - edhub360

  courses:
    build: ./courses
    restart: unless-stopped
    env_file: ./courses/env.prod
    depends_on:
      - cloud-sql-proxy
    ports:
      - "127.0.0.1:8009:8080"
    networks:
      - edhub360

networks:
  edhub360:
    driver: bridge

volumes:
  ai_chat_data:
