steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build', 
        '-t', 'us-central1-docker.pkg.dev/arctic-sentry-467317-s7/login-repo/login-service:${SHORT_SHA}-${BUILD_ID}', 
        './login'
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push', 
        'us-central1-docker.pkg.dev/arctic-sentry-467317-s7/login-repo/login-service:${SHORT_SHA}-${BUILD_ID}'
      ]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy login-service \
          --image=us-central1-docker.pkg.dev/arctic-sentry-467317-s7/login-repo/login-service:${SHORT_SHA}-${BUILD_ID} \
          --platform=managed \
          --region=us-central1 \
          --allow-unauthenticated \
          --memory=1Gi \
          --cpu=1 \
          --timeout=300 \
          --max-instances=10 \
          --port=8080 \
          --add-cloudsql-instances=arctic-sentry-467317-s7:us-central1:studenthub \
          --set-env-vars="DB_ECHO=false,ACCESS_TOKEN_EXPIRE_MINUTES=15,REFRESH_TOKEN_EXPIRE_DAYS=30,BCRYPT_ROUNDS=12,RATE_LIMIT_REQUESTS=5,APP_NAME=Auth Microservice,DEBUG=true,CORS_ORIGINS=["http://localhost:3000","https://www.alconsultingltd.com"]" \
          --update-secrets=DATABASE_URL=DATABASE_URL:latest,JWT_SECRET_KEY=JWT_SECRET_KEY:latest,JWT_ALGORITHM=JWT_ALGORITHM:latest,GOOGLE_CLIENT_ID=GOOGLE_CLIENT_ID:latest

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

images:
  - 'us-central1-docker.pkg.dev/arctic-sentry-467317-s7/login-repo/login-service:${SHORT_SHA}-${BUILD_ID}'
