steps:
  # 1. Build and push Notes backend
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'us-central1-docker.pkg.dev/arctic-sentry-467317-s7/notebook-repo/notebook-service:${SHORT_SHA}-${BUILD_ID}', 
      './Notes'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      'us-central1-docker.pkg.dev/arctic-sentry-467317-s7/notebook-repo/notebook-service:${SHORT_SHA}-${BUILD_ID}'
    ]
  # 3. Deploy to Cloud Run using secrets from Secret Manager
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        export DATABASE_URL=$(gcloud secrets versions access latest --secret="DATABASE_URL")
        export LOGIN_SERVICE_URL=$(gcloud secrets versions access latest --secret="LOGIN_SERVICE_URL")
        export GCS_BUCKET=$(gcloud secrets versions access latest --secret="GCS_BUCKET")
        export GEMINI_API_KEY=$(gcloud secrets versions access latest --secret="GEMINI_API_KEY")
        gcloud run deploy notebook-service \
          --region=us-central1 \
          --image=us-central1-docker.pkg.dev/arctic-sentry-467317-s7/notebook-repo/notebook-service:${SHORT_SHA}-${BUILD_ID} \
          --platform=managed \
          --allow-unauthenticated \
          --memory=1Gi --cpu=1 --timeout=300 --max-instances=10 --port=8080 \
          --add-cloudsql-instances=arctic-sentry-467317-s7:us-central1:studenthub \
          --set-env-vars=DATABASE_URL=$DATABASE_URL,LOGIN_SERVICE_URL=$LOGIN_SERVICE_URL,GCS_BUCKET=$GCS_BUCKET,GEMINI_API_KEY=$GEMINI_API_KEY

options:
  # logging: CLOUD_LOGGING_ONLY # This is commented out.
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/notebook-repo/notebook-service:${SHORT_SHA}-${BUILD_ID}'
