steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'us-central1-docker.pkg.dev/arctic-sentry-467317-s7/flashcard-repo/flashcard-service:${SHORT_SHA}-${BUILD_ID}', 
      './flashcard'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      'us-central1-docker.pkg.dev/arctic-sentry-467317-s7/flashcard-repo/flashcard-service:${SHORT_SHA}-${BUILD_ID}'
    ]

options:
  # logging: CLOUD_LOGGING_ONLY # This is commented out.
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/flashcard-repo/flashcard-service:${SHORT_SHA}-${BUILD_ID}'
