steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'us-central1-docker.pkg.dev/arctic-sentry-467317-s7/flashcard-repo/flashcard-service:${SHORT_SHA}-${BUILD_ID}', 
      './flashcard'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      'us-central1-docker.pkg.dev/arctic-sentry-467317-s7/flashcard-repo/flashcard-service:${SHORT_SHA}-${BUILD_ID}'
    ]
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        export DATABASE_URL=$(gcloud secrets versions access latest --secret="DATABASE_URL")
        gcloud run deploy flashcard-service \
          --region=us-central1 \
          --image=us-central1-docker.pkg.dev/arctic-sentry-467317-s7/flashcard-repo/flashcard-service:${SHORT_SHA}-${BUILD_ID} \
          --platform=managed \
          --allow-unauthenticated \
          --port=8080 \
          --set-env-vars=DATABASE_URL=$${DATABASE_URL}
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/flashcard-repo/flashcard-service:${SHORT_SHA}-${BUILD_ID}'
