name: Deploy Backend to Cloud Run

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker asia-south1-docker.pkg.dev --quiet

      - name: Build and Push Docker image
        run: |
          docker build -t asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ai-chat-repo/ai-chat-service:${{ github.sha }} .
          docker push asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ai-chat-repo/ai-chat-service:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ai-chat-service \
            --image asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ai-chat-repo/ai-chat-service:${{ github.sha }} \
            --region asia-south1 \
            --platform managed \
            --allow-unauthenticated \
            --port 8080
